### ISSUE TITLE
activate GitHub pages

### ISSUE THREAD

**Issue by jkowalleck** [susam/spcss#1]
could you activate GitHub's "pages" option in the settings of this repo so github hosts this repo as a web page? 
This would make it easy to see how the `cp.css` looks in action.

**Comment by jcubic** [comment]
There is github pages already, maybe it should be linked as home page https://susam.github.io/spcss/

I would add twitter card and Facebook open graph images so it look better on twitter and Facebook. So you get more users because less people will click the link.

**NOTE** you can also add image to GitHub repo in settings so it will attract more users.

**Comment by jkowalleck** [comment]
i see.
closed this ticket, since demo link in reame is now clearer and links to github oages,
